version: '3'
services:
  web:
    image: nginx:1.13.7
    volumes:
     - ./web:/usr/share/nginx/html
    ports:
     - "8080:80"
  api:
    build: ./api/
    depends_on:
     - db
    ports:
     - "3000:3000"
  db:
    image: mongo:3.6.0
